version: "3.7"

services:
  xca:
    container_name: xca
    image: alexandreoda/xca
    restart: "no"
    privileged: false
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - "${HOME}:/home/xca"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"